# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: zavastore
metadata:
  template: zavastore@0.0.1-beta

services:
  web:
    project: ./src
    language: csharp
    host: appservice
    docker:
      path: ./Dockerfile
      context: ./src

infra:
  provider: bicep
  path: infra
  module: main

hooks:
  preprovision:
    run: echo "Preparing to provision Azure resources..."
  postprovision:
    run: echo "Azure resources provisioned successfully"
    
pipeline:
  provider: github
